### PR TITLE
converted to py3 using 2to3

### LINKED ISSUE #26: URLerror
Hello,

I tried one both examples in readme: e.g. `seedlink-plotter -s "G_MBO:00BHZ" -b 10m --seedlink_server "rtserver.ipgp.fr:18000"  --line_plot`

And I get the following error:
```
Traceback (most recent call last):
  File "/Users/sph1r17/anaconda/bin/seedlink-plotter", line 11, in <module>
    load_entry_point('seedlink-plotter==0.1.0', 'console_scripts', 'seedlink-plotter')()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/seedlink_plotter/seedlink_plotter.py", line 420
    except URLError, error:
```

### PR DESCRIPTION
**Pull request by rsignell-usgs**
fixes #26 

All I did was: 
```
2to3 -w seedlink_plotter
```

### CODE REVIEW

**Comment by megies** [comment]
..but then it's not Py2 compatible any more, I guess?

**Comment by rsignell-usgs** [comment]
Good point.  Yes, that's true.    

Could look at this as tough love:  folks really shouldn't be using py2 anyway these days -- it's too embarrassing!  :smile_cat:

**Comment by megies** [comment]
Well, it's only so few instances, would be easy to accommodate with a couple of if/else/import-as at the top..

**Comment by rsignell-usgs** [comment]
maybe `import six` would handle most of these.

**Comment by megies** [comment]
I haven't used `six` a lot, but we have our experiences with `future` (and they are painful in the long run). In general, if it's only a couple of instances like here, just doing a conditional import at the top with renaming some imported items is by far the simplest solution. KISS.

**Pull request closed without merging**
